version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - chmod -R 755 .
      - mvn clean test
      - echo Build completed on `date`

  post_build:
    commands:
      - echo Deploy completed on `date`

#reports:
#  JUnitReports: # CodeBuild will create a report group called "SurefireReports".
#    files: #Store all of the files
#      - '**/*'
#    base-directory: '/report' # Location of the reports